name: Matthew Coleman
theme: jekyll-theme-minimal
markdown: kramdown
#title: Matthew Coleman
#description: Here you can find out a bit about me and see my project highlights (plus fun stuff at the bottom)
