theme: jekyll-theme-minimal
title: Matthew Coleman
#description: Here you can find out a bit about me and see my project highlights (plus fun stuff at the bottom)
tabs: 
    tab1:
        name: foo
        title: Page One
        source: source1
    tab2:
        name: bar
        title: Page Two
        source: source2
        content: >
            ## Headline

            This is the content of the second tab, it is defined in the frontmatter as **markdown**.

#            A Link: [link](https://foo.bar.org)
    tab3:
        name: baz
        title: Page Three
        active: 1
        source: source3