theme: jekyll-theme-minimal
title: Matthew Coleman
markdown: bookdown
description: Here you can find out a bit about me and see my project highlights (plus fun stuff at the bottom)
output: html_document